name: Lint and Format

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4

  javaformat:
    name: "Java format"
    runs-on: ubuntu-22.04
    needs: [validation]
    container: wpilib/ubuntu-base:22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all history and metadata
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Check Java format
        run: ./gradlew spotlessApply
      - name: Check output
        run: git --no-pager diff --exit-code HEAD
      - name: Generate diff
        run: git diff HEAD > javaformat-fixes.patch
        if: ${{ failure() }}
      - uses: actions/upload-artifact@v4
        with:
          name: javaformat fixes
          path: javaformat-fixes.patch
        if: ${{ failure() }}
      - name: Write to job summary
        run: |
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          cat javaformat-fixes.patch >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        if: ${{ failure() }}
